version: "3.3"
services:
  hwschematic:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./examples:/home/d3-hwschematic/examples
      - ./index.html:/home/d3-hwschematic/index.html
    working_dir: /home/d3-hwschematic
    command: python3 -m http.server 8081
